[package]
name = "poe"
version = "0.1.0"
authors = ["Kazuki Yamaguchi <k@rhe.jp>"]

[features]
default = []

[dependencies]
iron = "*"
router = "*"
rustc-serialize = "*"
rust-crypto = "*"
uuid = "*"
time = "*"
byteorder = "*"
